trigger:
  branches:
    include:
      - cach

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'mahmoudalsory/todoapp'
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn/cache
  npm_config_cache: $(Pipeline.Workspace)/.npm

steps:
# ----------------------------
# 1. Setup Node.js (consider upgrading to LTS)
# ----------------------------
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # Updated to LTS version
  displayName: 'Install Node.js'

# ----------------------------
# 2. Cache Yarn packages (more efficient approach)
# ----------------------------
- task: Cache@2
  inputs:
    key: 'yarn | "$(Agent.OS)" | yarn.lock'
    restoreKeys: |
      yarn | "$(Agent.OS)"
    path: |
      $(YARN_CACHE_FOLDER)
      node_modules
  displayName: 'Cache Yarn packages'

# ----------------------------
# 3. Yarn Install with optimized flags
# ----------------------------
- script: |
    yarn install --immutable --immutable-cache --check-cache
  displayName: 'Yarn Install (optimized)'

# ----------------------------
# 4. Build the app
# ----------------------------
- script: yarn build
  displayName: 'Build App'

# ----------------------------
# 5. Docker Login
# ----------------------------
- script: |
    echo "$(DOCKERHUB_PASSWORD)" | docker login -u "$(DOCKERHUB_USERNAME)" --password-stdin
  displayName: 'Docker Login'

# ----------------------------
# 6. Docker Build & Push
# ----------------------------
- script: |
    docker build -t $(imageName):latest .
    docker push $(imageName):latest
  displayName: 'Build & Push Docker Image'

# ----------------------------
# 7. Run & Test the Container
# ----------------------------
- script: |
    echo "Running container locally on agent..."
    docker run -d -p 90:80 --name test-container $(imageName):latest

    echo "Waiting for app to start..."
    sleep 5

    echo "Testing with curl:"
    curl -I http://localhost:90 || echo "App did not respond!"

    echo "Logs from the container:"
    docker logs test-container || true

    echo "Cleaning up..."
    docker stop test-container && docker rm test-container
  displayName: 'Run Docker Container & Test'
