trigger:
  branches:
    include:
      - cach

variables:
  dockerImageName: 'mahmoudalsory/todo-app'
  dockerImageTag: 'latest'
  dockerCacheTag: 'buildcache'

stages:
  - stage: BuildAndPush
    displayName: 'Build and Push Docker Image with Buildx Cache'
    jobs:
      - job: DockerBuild
        displayName: 'Docker Build & Push'
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - task: DockerInstaller@0
            inputs:
              dockerVersion: '20.10.7'

          - script: |
              echo "Creating and using buildx builder..."
              docker buildx create --use --name mybuilder || docker buildx use mybuilder
            displayName: 'Create Docker Buildx Builder'

          - script: |
              echo $(DOCKERHUB_PASSWORD) | docker login -u $(DOCKERHUB_USERNAME) --password-stdin
            displayName: 'Login to Docker Hub with Password'

          - script: |
              docker buildx build \
                --build-arg BUILDKIT_INLINE_CACHE=1 \
                --cache-from=type=registry,ref=$(dockerImageName):$(dockerCacheTag) \
                --cache-to=type=registry,ref=$(dockerImageName):$(dockerCacheTag),mode=max \
                -t $(dockerImageName):$(dockerImageTag) \
                --push .
            displayName: 'Build and Push with Remote Cache'
