trigger:
- main  # Trigger the pipeline on changes to the main branch

variables:
  dockerHubImage: 'mahmoudalsory/todoapp'  # Your Docker Hub image name
  containerName: 'todo-app-container'     # Name of the running container

pool:
  vmImage: 'ubuntu-latest'  # Use the free Ubuntu agent provided by Azure DevOps

stages:
- stage: Deploy
  displayName: 'Deploy Application'
  jobs:
  - job: DeployJob
    steps:
    - script: |
        echo "Pulling Docker image from Docker Hub..."
        docker pull $(dockerHubImage):latest
      displayName: 'Pull Docker Image from Docker Hub'

    - script: |
        echo "Stopping and removing any existing container with the same name..."
        docker stop $(containerName) || true
        docker rm $(containerName) || true
      displayName: 'Stop and Remove Existing Container'

    - script: |
        echo "Running the Docker container..."
        docker run -d --name $(containerName) -p 90:80 $(dockerHubImage):latest
      displayName: 'Run Docker Container'

- stage: Notify
  displayName: 'Post Deployment Notification'
  dependsOn: Deploy
  condition: always()  # Always run this stage regardless of success or failure
  jobs:
  - job: NotifyJob
    steps:
    - script: |
        if [ "$(Agent.JobStatus)" == "Succeeded" ]; then
          echo "Deployment successful!"
        else
          echo "Deployment failed!"
        fi
      displayName: 'Notify Deployment Status'
