trigger:
  branches:
    include:
      - cach

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'mahmoudalsory/todoapp'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

# Cache node_modules
- task: Cache@2
  inputs:
    key: 'yarn | "$(Agent.OS)" | yarn.lock'
    path: node_modules
    restoreKeys: |
      yarn | "$(Agent.OS)"
  displayName: 'Cache node_modules'

# Install dependencies
- script: |
    yarn install --frozen-lockfile
  displayName: 'Yarn Install'

# Cache dist/ folder
- task: Cache@2
  inputs:
    key: 'build | "$(Agent.OS)" | yarn.lock'
    path: dist
    restoreKeys: |
      build | "$(Agent.OS)"
  displayName: 'Cache dist'

# Build app
- script: |
    yarn build
  displayName: 'Yarn Build'

# Login to Docker Hub
- script: |
    echo "$(DOCKERHUB_PASSWORD)" | docker login -u "$(DOCKERHUB_USERNAME)" --password-stdin
  displayName: 'Docker Login'

# Build and Push Docker image
- script: |
    docker build -t $(imageName):latest .
    docker push $(imageName):latest
  displayName: 'Build and Push Docker Image'
