stages:
  - stage: BuildAndDeploy
    displayName: 'Build and Deploy'
    jobs:
      - job: BuildAndRunJob
        displayName: 'Build and Run'
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - task: UseNode@1
            inputs:
              version: '14.x'

          - script: |
              yarn install --frozen-lockfile
              yarn build
            displayName: 'Install & Build App'

          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              command: 'build'
              Dockerfile: '**/Dockerfile'
              tags: |
                todo-app:$(Build.BuildId)

          - script: |
              docker run -d -p 90:80 todo-app:$(Build.BuildId)
            displayName: 'Run Docker Container'
