trigger:
  branches:
    include:
      - cach

variables:
  imageName: 'mahmoudalsory/todoapp'
  cacheTag: 'buildcache-$(Build.SourceBranchName)'
  dockerfilePath: 'Dockerfile'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '20.10.7'
  displayName: 'Install Docker'

- script: |
    echo "$(DOCKERHUB_PASSWORD)" | docker login -u "$(DOCKERHUB_USERNAME)" --password-stdin
  displayName: 'Login to Docker Hub'
  env:
    DOCKERHUB_PASSWORD: $(DOCKERHUB_PASSWORD)
    DOCKERHUB_USERNAME: $(DOCKERHUB_USERNAME)

- script: |
    docker buildx create --use --name builder
    docker buildx inspect --bootstrap
    docker buildx ls
  displayName: 'Setup Buildx Builder'

- script: |
    docker buildx build \
      --builder builder \
      --file $(dockerfilePath) \
      --tag $(imageName):latest \
      --tag $(imageName):$(Build.BuildId) \
      --cache-from=type=registry,ref=$(imageName):$(cacheTag) \
      --cache-to=type=registry,ref=$(imageName):$(cacheTag),mode=max \
      --build-arg BUILDKIT_INLINE_CACHE=1 \
      --push \
      .
  displayName: 'Build and Push with Cache'

- script: |
    echo "Verifying cache usage..."
    docker buildx build \
      --builder builder \
      --file $(dockerfilePath) \
      --tag $(imageName):cache-test \
      --cache-from=type=registry,ref=$(imageName):$(cacheTag) \
      --load \
      --progress plain \
      .
    docker history $(imageName):cache-test
  displayName: 'Verify Cache Usage'
