trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  DOCKER_IMAGE_NAME: 'todo-app'
  DOCKER_IMAGE_TAG: '$(Build.BuildId)'  # Unique tag for each build

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - checkout: self
    - script: |
        docker build -t $(DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG) .
      displayName: 'Build Docker Image'

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: |
        echo "Running Docker container..."
        docker run -d -p 90:80 $(DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG)
      displayName: 'Run Docker Container'
