trigger:
  branches:
    include:
      - main  # or your default branch

variables:
  dockerImageName: 'todo-app'

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildJob
        displayName: 'Build and Push Docker Image'
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - task: GitClone@1
            inputs:
              repository: 'https://github.com/mahmoudsory/todo-app.git'

          - task: UseNode@1
            inputs:
              version: '14.x'

          - script: |
              yarn install --frozen-lockfile
              yarn build
            displayName: 'Install Dependencies and Build App'

          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              command: 'build'
              Dockerfile: '**/Dockerfile'
              tags: |
                $(dockerImageName):$(Build.BuildId)

  - stage: Deploy
    displayName: 'Deploy Stage'
    dependsOn: Build
    jobs:
      - job: DeployJob
        displayName: 'Run Docker Container'
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - script: |
              docker run -d -p 90:80 $(dockerImageName):$(Build.BuildId)
            displayName: 'Run Docker Container'
