trigger:
- main  # Trigger the pipeline on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image for the build agent

variables:
  dockerImageName: 'todo-app'  # Base name for the Docker image
  buildId: $(Build.BuildId)  # Unique build ID provided by Azure DevOps

steps:

- task: UseNode@1
  inputs:
    version: '14.x'  # Use Node.js version 14
  displayName: 'Use Node.js 14'

- script: |
    echo "Installing dependencies..."
    yarn install --frozen-lockfile
    echo "Building the application..."
    yarn build
  displayName: 'Install Dependencies and Build'

- script: |
    echo "Building Docker image..."
    docker build -t $(dockerImageName):$(buildId) .
  displayName: 'Build Docker Image'

- script: |
    echo "Running Docker container..."
    docker run -d -p 90:80 $(dockerImageName):$(buildId)
  displayName: 'Run Docker Container'

- script: |
    echo "Testing the application..."
    curl http://localhost:90
  displayName: 'Test Application'

- script: |
    echo "Deployment successful!"
  condition: succeeded()
  displayName: 'Deployment Success'

- script: |
    echo "Deployment failed!"
  condition: failed()
  displayName: 'Deployment Failure'
