trigger:
  branches:
    include:
      - cach

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'mahmoudalsory/todoapp'
  cacheTag: 'buildcache'

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '20.10.7'

- script: |
    echo "$(DOCKERHUB_PASSWORD)" | docker login -u "$(DOCKERHUB_USERNAME)" --password-stdin
  displayName: 'Login to Docker Hub'

- script: |
    docker buildx create --use --name builder
    docker buildx inspect --bootstrap
  displayName: 'Setup Docker Buildx'

- script: |
    echo "Trying to pull build cache image..."
    docker pull $(imageName):$(cacheTag) || echo "No cache found. Building from scratch."
  displayName: 'Pull Cache Layer (Optional)'

- script: |
    docker buildx build \
      --builder builder \
      --tag $(imageName):latest \
      --tag $(imageName):$(cacheTag) \
      --cache-from=type=registry,ref=$(imageName):$(cacheTag) \
      --cache-to=type=registry,ref=$(imageName):$(cacheTag),mode=max \
      --build-arg BUILDKIT_INLINE_CACHE=1 \
      --push \
      --file Dockerfile \
      --progress=plain \
      .
  displayName: 'Build & Push with Remote Caching (BuildKit)'

# Optional Test Container on Agent
- script: |
    echo "Pulling image and running container locally on agent..."
    docker run -d -p 90:80 --name test-container $(imageName):latest

    echo "Waiting for container to start..."
    sleep 5

    echo "Testing with curl:"
    curl -I http://localhost:90 || echo "App did not respond!"

    echo "Showing container logs:"
    docker logs test-container || true

    echo "Stopping and cleaning up..."
    docker stop test-container && docker rm test-container
  displayName: 'Temporary Deploy & Test Container on Azure Agent'
