# azure-pipelines.yml
trigger:
- main  # Adjust the branch as needed

variables:
  DOCKER_IMAGE: 'todo-app:$(Build.BuildId)'  # Set the Docker image name with a unique build ID

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image

stages:
- stage: Build
  displayName: 'Build Docker Image'
  jobs:
  - job: Build
    displayName: 'Build Docker Image'
    steps:
    - checkout: self  # Clone the repository

    - script: |
        echo "Building Docker image..."
        docker build -t $(DOCKER_IMAGE) .  # Build the Docker image
      displayName: 'Build Docker Image'

- stage: Deploy
  displayName: 'Deploy Docker Container'
  jobs:
  - job: Deploy
    displayName: 'Run Docker Container'
    steps:
    - script: |
        echo "Running Docker container..."
        docker run -d -p 90:80 $(DOCKER_IMAGE)  # Run the Docker container and map ports
      displayName: 'Run Docker Container'
