trigger:
- main 

variables:
  dockerHubImage: 'mahmoudalsory/todoapp' 
  containerName: 'todo-app-container-$(Build.BuildId)' 
  imageTag: 'v1'                          

pool:
  vmImage: 'ubuntu-latest' 

stages:
- stage: Deploy
  displayName: 'Deploy Application'
  jobs:
  - job: DeployJob
    steps:
    - script: |
        echo "Pulling Docker image from Docker Hub..."
        docker pull $(dockerHubImage):$(imageTag)
      displayName: 'Pull Docker Image from Docker Hub'

    - script: |
        echo "Running the Docker container..."
        docker run -d --name $(containerName) -p 90:80 $(dockerHubImage):$(imageTag)
      displayName: 'Run Docker Container'
