trigger:
  branches:
    include:
      - cach

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'mahmoudalsory/todoapp'

steps:
# ----------------------------
# 1. Setup Node.js
# ----------------------------
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

# ----------------------------
# 2. Restore Yarn Offline Cache
# ----------------------------
- script: |
    mkdir -p .yarn-cache
    cp -r $(Pipeline.Workspace)/.yarn-cache/* .yarn-cache/ || true
  displayName: 'Restore Yarn Offline Cache'

# ----------------------------
# 3. Cache Yarn Tarballs
# ----------------------------
- task: Cache@2
  inputs:
    key: 'yarn-tarballs | "$(Agent.OS)" | yarn.lock'
    path: .yarn-cache
    restoreKeys: |
      yarn-tarballs | "$(Agent.OS)"
  displayName: 'Cache Yarn Tarballs'

# ----------------------------
# 4. Cache node_modules
# ----------------------------
- task: Cache@2
  inputs:
    key: 'yarn-modules | "$(Agent.OS)" | yarn.lock'
    path: node_modules
    restoreKeys: |
      yarn-modules | "$(Agent.OS)"
  displayName: 'Cache node_modules'

# ----------------------------
# 5. Yarn Install
# ----------------------------
- script: |
    yarn config set yarn-offline-mirror .yarn-cache
    yarn install --frozen-lockfile --prefer-offline --immutable
  displayName: 'Yarn Install with Offline Cache'

# ----------------------------
# 6. Cache dist/ folder
# ----------------------------
- task: Cache@2
  inputs:
    key: 'build-dist | "$(Agent.OS)" | yarn.lock | webpack.config.js'
    path: dist
    restoreKeys: |
      build-dist | "$(Agent.OS)"
  displayName: 'Cache dist folder'

# ----------------------------
# 7. Build the app
# ----------------------------
- script: yarn build
  displayName: 'Build App'

# ----------------------------
# 8. Docker Login
# ----------------------------
- script: |
    echo "$(DOCKERHUB_PASSWORD)" | docker login -u "$(DOCKERHUB_USERNAME)" --password-stdin
  displayName: 'Docker Login'

# ----------------------------
# 9. Docker Build & Push
# ----------------------------
- script: |
    docker build -t $(imageName):latest .
    docker push $(imageName):latest
  displayName: 'Build & Push Docker Image'

# ----------------------------
# 10. Run & Test the Container
# ----------------------------
- script: |
    echo "Running container locally on agent..."
    docker run -d -p 90:80 --name test-container $(imageName):latest

    echo "Waiting for app to start..."
    sleep 5

    echo "Testing with curl:"
    curl -I http://localhost:90 || echo "App did not respond!"

    echo "Logs from the container:"
    docker logs test-container || true

    echo "Cleaning up..."
    docker stop test-container && docker rm test-container
  displayName: 'Run Docker Container & Test'
