trigger:
  branches:
    include:
      - cach

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'mahmoudalsory/todoapp'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

# Optional Yarn offline mirror cache
- task: Cache@2
  inputs:
    key: 'yarn-cache | "$(Agent.OS)" | yarn.lock'
    path: .yarn-cache
    restoreKeys: |
      yarn-cache | "$(Agent.OS)"
  displayName: 'Cache Yarn Tarballs'

# Cache node_modules for faster yarn install
- task: Cache@2
  inputs:
    key: 'yarn | "$(Agent.OS)" | yarn.lock'
    path: node_modules
    restoreKeys: |
      yarn | "$(Agent.OS)"
  displayName: 'Cache node_modules'

# Yarn install with offline preference
- script: |
    yarn config set yarn-offline-mirror .yarn-cache
    yarn install --frozen-lockfile --prefer-offline
  displayName: 'Yarn Install with Offline Cache'

# Cache build output (dist/) if needed later
- task: Cache@2
  inputs:
    key: 'build | "$(Agent.OS)" | yarn.lock'
    path: dist
    restoreKeys: |
      build | "$(Agent.OS)"
  displayName: 'Cache dist/ build folder'

# Build the app
- script: |
    yarn build
  displayName: 'Build App'

# Docker login
- script: |
    echo "$(DOCKERHUB_PASSWORD)" | docker login -u "$(DOCKERHUB_USERNAME)" --password-stdin
  displayName: 'Docker Login'

# Docker build and push (dist/ already built)
- script: |
    docker build -t $(imageName):latest .
    docker push $(imageName):latest
  displayName: 'Build & Push Docker Image'

# Test the Docker container
- script: |
    echo "Running container locally on agent..."
    docker run -d -p 90:80 --name test-container $(imageName):latest

    echo "Waiting for app to start..."
    sleep 5

    echo "Testing with curl:"
    curl -I http://localhost:90 || echo "App did not respond!"

    echo "Logs from the container:"
    docker logs test-container || true

    echo "Stopping and removing container..."
    docker stop test-container && docker rm test-container
  displayName: 'Run Docker Container & Test'
